import RequestProject.Aqt.ThetaHom

/-!
# `Θ` preserves the kernel of the action (`lem:preserve_kernel`)

The action of `𝒜_{q,t}` on
`V = ⨁_k Λ ⊗ 𝕜[y^{±1}]` has kernel generated by

* `(I1)` `(d_- d_+^* - 1) (d_+^*)^k ε_0 = 0`, and
* `(I2)` `(d_+ + q^k y_1 d_+^*) (d_+^*)^k ε_0 = 0`.

This file proves the general-level preservation statements, together with the
key lemma `sStar_acts_as_0`.  For `k ≥ 1`, the latter says that `s^*` annihilates
`(d_+^*)^k ε₀`.  Consequently `minv = (1+s*)⁻¹` fixes these vectors and
`Θ(d_+^*)^k ε₀ = (d_+^*)^k ε₀` (`theta_dps_pow_eq`).  The preservation of `(I1)`
and `(I2)` then reduces directly to the original level-`k` relations.

The level-graded `(I2)` and `(Q2)` instances used to establish
`sStar_acts_as_0` are explicit hypotheses, since the surrounding development is
a single-generic-level presentation.  The scalar operator theorem
`theta_I2_operator_scalar` proves
`Θ(d_+) + a Θ(y_1)Θ(d_+^*) = d_+ + a y_1d_+^*` when the corresponding `(Q2)`
constant is `-a`.  Its specialization `a = q^k` yields the source's arbitrary-level `(I2)` result.
-/

namespace DyckAlgebra

namespace DyckRepU

variable {𝕜 : Type*} [Field 𝕜] {q cQ2 : 𝕜} (ρ : DyckRepU 𝕜 q cQ2)

/-
`w₁ - 1 = -u • (w₁ y₁)`, the geometric-series step.
-/
lemma w1_sub_one : ρ.w 1 - 1 = -(ρ.u • (ρ.w 1 * ρ.yy 1)) := by
  have := ρ.wL 1;
  simp_all +decide [ add_mul, mul_assoc, DyckRepU.w_comm_yy ];
  exact eq_neg_of_add_eq_zero_left ( by rw [ ← this ] ; abel1 )

/-
**Scalar form of the `(I2)` operator identity.**

At a level where `(Q2)` has unnormalised structure constant
`cQ2 = -a`, the `Θ`-image of `d_+ + a y_1 d_+^*` is exactly that
same operator.  Taking `a = q^k` gives the level-`k` relation in the source.
-/
lemma theta_I2_operator_scalar (a : 𝕜) (hcQ2 : cQ2 = -a) :
    ρ.Θdp + a • (ρ.Θy1 * ρ.Θdps) = ρ.dp + a • (ρ.yy 1 * ρ.dps) := by
  unfold DyckRepU.Θdp DyckRepU.Θy1 DyckRepU.Θdps;
  have h_sStar_dp : ρ.u • (ρ.w 1 * ρ.yy 1 * ρ.zz 1) * ρ.dp = -a • (ρ.u • (ρ.w 1 * ρ.yy 1 * ρ.yy 1) * ρ.dps) := by
    have := ρ.Q2; simp_all +decide [ mul_assoc, smul_smul ] ;
    rw [ mul_comm ];
  have h_sStar_dp : (1 - ρ.u • (ρ.w 1 * ρ.yy 1 * ρ.zz 1)) * ρ.dp = ρ.dp - (-a • (ρ.u • (ρ.w 1 * ρ.yy 1 * ρ.yy 1) * ρ.dps)) := by
    rw [ ← h_sStar_dp, sub_mul, one_mul ];
  have h_sStar_dp : (1 - ρ.u • (ρ.w 1 * ρ.yy 1 * ρ.zz 1)) * ρ.yy 1 * (ρ.minv * ρ.dps) = ρ.w 1 * ρ.yy 1 * ρ.dps := by
    convert DyckRepU.theta_y1_dps ρ using 1;
  have h_sStar_dp : ρ.w 1 * ρ.yy 1 * ρ.dps = ρ.yy 1 * ρ.dps - ρ.u • (ρ.w 1 * ρ.yy 1 * ρ.yy 1) * ρ.dps := by
    have h_sStar_dp : ρ.w 1 * ρ.yy 1 * (1 + ρ.u • ρ.yy 1) * ρ.dps = ρ.yy 1 * ρ.dps := by
      have := ρ.w1_yy1_one_add;
      rw [this];
    simp_all +decide [ mul_add, add_mul, mul_assoc ];
    exact eq_sub_of_add_eq h_sStar_dp;
  simp_all +decide [ DyckRepU.sElt ];
  simp +decide [ add_assoc, smul_sub ]

/-
**`lem:s*_acts_as_0`.**  For `k ≥ 1`, `s^*` annihilates `(d_+^*)^k ε₀`.

The hypotheses `hI2` and `hQ2` are the level-graded instantiations of `(I2)` and
`(Q2)` used in the paper's proof (the "by (I2)" and "by (Q2)" steps):

* `hI2`:  `y₁ (d_+^*)^k ε₀ = -q^{-k} · d_+ (d_+^*)^{k-1} ε₀`;
* `hQ2`:  `z₁ · (d_+ (d_+^*)^{k-1} ε₀) = -q^k · y₁ (d_+^*)^k ε₀`.

The hypothesis `_hk : 1 ≤ k` records that the lemma is stated "for `k ≥ 1`" (for
`k = 0` one has `s^* ≠ 0`); it is kept for faithfulness even though, once the
level-graded facts `hI2`/`hQ2` are supplied as hypotheses, the algebraic proof no
longer needs it.
-/
theorem sStar_acts_as_0 (k : ℕ) (_hk : 1 ≤ k) (e0 : ρ.carrier)
    (hq : q ≠ 0)
    (hI2 : ρ.yy 1 * ρ.dps ^ k * e0
        = (-(q ^ k)⁻¹) • (ρ.dp * ρ.dps ^ (k - 1) * e0))
    (hQ2 : ρ.zz 1 * (ρ.dp * ρ.dps ^ (k - 1) * e0)
        = (-(q ^ k)) • (ρ.yy 1 * ρ.dps ^ k * e0)) :
    ρ.sStarElt * ρ.dps ^ k * e0 = 0 := by
  unfold DyckRepU.sStarElt;
  simp_all +decide [mul_assoc, sub_mul, smul_smul]

/-
If `s^*` annihilates `(d_+^*)^j ε₀`, then `minv = (1+s*)⁻¹` fixes it.
-/
theorem minv_mul_dps_pow (j : ℕ) (e0 : ρ.carrier)
    (hsStar : ρ.sStarElt * ρ.dps ^ j * e0 = 0) :
    ρ.minv * ρ.dps ^ j * e0 = ρ.dps ^ j * e0 := by
  have h_sStarElt : (1 + ρ.sStarElt) * (ρ.dps ^ j * e0) = ρ.dps ^ j * e0 := by
    simp_all +decide [ add_mul, mul_assoc ];
  have h_minv : ρ.minv * (1 + ρ.sStarElt) = 1 := by
    exact ρ.mR;
  have h_minv : ρ.minv * (ρ.dps ^ j * e0) = ρ.minv * ((1 + ρ.sStarElt) * (ρ.dps ^ j * e0)) := by
    rw [h_sStarElt];
  rw [ mul_assoc, h_minv, ← mul_assoc, ‹ρ.minv * ( 1 + ρ.sStarElt ) = 1›, one_mul ]

/-
Since `minv` fixes every `(d_+^*)^j ε₀` (`j ≥ 1`), we have
`Θ(d_+^*)^k ε₀ = (d_+^*)^k ε₀`.
-/
theorem theta_dps_pow_eq (k : ℕ) (e0 : ρ.carrier)
    (hsStar : ∀ j, 1 ≤ j → ρ.sStarElt * ρ.dps ^ j * e0 = 0) :
    ρ.Θdps ^ k * e0 = ρ.dps ^ k * e0 := by
  induction' k with k ih;
  · simp +decide;
  · convert minv_mul_dps_pow ρ ( k + 1 ) e0 ( hsStar ( k + 1 ) ( Nat.succ_pos k ) ) using 1;
    convert congr_arg ( fun x => ρ.minv * ρ.dps * x ) ih using 1 <;> simp +decide [ pow_succ', mul_assoc ];
    simp +decide [ ← mul_assoc, DyckRepU.Θdps ]

/--
**`Θ` preserves the relation (I1) at an arbitrary level `k`** — the general case,
keeping the `(d_+^*)^k` factor.

Given that `s^*` annihilates every `(d_+^*)^j ε₀` (`j ≥ 1`) and the level-`k`
relation `(d_- d_+^* - 1)(d_+^*)^k ε₀ = 0`, the `Θ`-image
`(d_- Θ(d_+^*) - 1) (Θ(d_+^*))^k ε₀` is again `0`.

The proof uses only `theta_dps_pow_eq`: since `Θ(d_+^*)^k ε₀ = (d_+^*)^k ε₀` (and
likewise at `k+1`), the `Θ`-image operator lands on the original level-`k`
relation.
-/
theorem theta_preserve_I1_via_sStar (k : ℕ) (e0 : ρ.carrier)
    (hsStar : ∀ j, 1 ≤ j → ρ.sStarElt * ρ.dps ^ j * e0 = 0)
    (hI1 : (ρ.dm * ρ.dps - 1) * ρ.dps ^ k * e0 = 0) :
    (ρ.dm * ρ.Θdps - 1) * ρ.Θdps ^ k * e0 = 0 := by
  have hk : ρ.Θdps ^ k * e0 = ρ.dps ^ k * e0 := ρ.theta_dps_pow_eq k e0 hsStar
  have hk1 : ρ.Θdps ^ (k + 1) * e0 = ρ.dps ^ (k + 1) * e0 :=
    ρ.theta_dps_pow_eq (k + 1) e0 hsStar
  have expand : (ρ.dm * ρ.Θdps - 1) * ρ.Θdps ^ k * e0
      = ρ.dm * (ρ.Θdps ^ (k + 1) * e0) - ρ.Θdps ^ k * e0 := by
    rw [pow_succ']; noncomm_ring
  have collapse : ρ.dm * (ρ.dps ^ (k + 1) * e0) - ρ.dps ^ k * e0
      = (ρ.dm * ρ.dps - 1) * ρ.dps ^ k * e0 := by
    rw [pow_succ']; noncomm_ring
  rw [expand, hk, hk1, collapse, hI1]

/--
**Scalar form of general-level `(I2)` preservation.**

This is the form needed by the source, whose level-`k` annihilator
relation is `(d_+ + q^k y_1 d_+^*) (d_+^*)^k ε₀ = 0`.  The scalar `a` is kept
general here; the corresponding level value of `(Q2)` is
`cQ2 = -a`.
-/
theorem theta_preserve_I2_scalar_via_sStar (a : 𝕜) (k : ℕ) (e0 : ρ.carrier)
    (hcQ2 : cQ2 = -a)
    (hsStar : ∀ j, 1 ≤ j → ρ.sStarElt * ρ.dps ^ j * e0 = 0)
    (hI2 : (ρ.dp + a • (ρ.yy 1 * ρ.dps)) * ρ.dps ^ k * e0 = 0) :
    (ρ.Θdp + a • (ρ.Θy1 * ρ.Θdps)) * ρ.Θdps ^ k * e0 = 0 := by
  calc (ρ.Θdp + a • (ρ.Θy1 * ρ.Θdps)) * ρ.Θdps ^ k * e0
      = (ρ.dp + a • (ρ.yy 1 * ρ.dps)) * (ρ.Θdps ^ k * e0) := by
        rw [ρ.theta_I2_operator_scalar a hcQ2, mul_assoc]
    _ = (ρ.dp + a • (ρ.yy 1 * ρ.dps)) * (ρ.dps ^ k * e0) := by
        rw [ρ.theta_dps_pow_eq k e0 hsStar]
    _ = 0 := by rw [← mul_assoc, hI2]

/--
**The source's level-`k` `(I2)` relation is preserved by `Θ`.**

Here the coefficient is exactly `q^k`, and `(Q2)` consequently has coefficient
`-q^k`.
-/
theorem theta_preserve_I2_qpow_via_sStar (k : ℕ) (e0 : ρ.carrier)
    (hcQ2 : cQ2 = -(q ^ k))
    (hsStar : ∀ j, 1 ≤ j → ρ.sStarElt * ρ.dps ^ j * e0 = 0)
    (hI2 : (ρ.dp + (q ^ k) • (ρ.yy 1 * ρ.dps)) * ρ.dps ^ k * e0 = 0) :
    (ρ.Θdp + (q ^ k) • (ρ.Θy1 * ρ.Θdps)) * ρ.Θdps ^ k * e0 = 0 := by
  exact ρ.theta_preserve_I2_scalar_via_sStar (q ^ k) k e0 hcQ2 hsStar hI2


end DyckRepU

end DyckAlgebra